spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}/blockchainthree?autoReconnect=true&useUnicode=true&useSSL=true
    username: root
    password: ${MYSQL_PASS}
server:
  port: 8080