spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockchainthree?autoReconnect=true&useUnicode=true&useSSL=true
    password: 19950604qwe
    username: root