spring:
  jpa:
    show-sql: false
    database-platform: com.mindata.blockchain.core.sqlite.config.SQLiteDialect
    generate-ddl: true

  # cache:
    # type: redis
  ##默认密码为空
  redis:
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    password: 19950604qwe
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 10
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0

sqlite:
  dbName: a.db  #本地sqlite的名字
db:
  levelDB: false    #在部分Windows机器上rocksDB会报错dll找不到，那么就用levelDB来替代
  rocksDB: true
singleNode: true  #如果是单节点测试，改成true
version: 1
name: ${NAME:maida}
appId: ${APP_ID:wolf}
managerUrl: ${MANAGER_URL:http://localhost:8888/}
publicKey: A8WLqHTjcT/FQ2IWhIePNShUEcdCzu5dG+XrQU8OMu54
privateKey: yScdp6fNgUU+cRUTygvJG4EBhDKmOMRrK4XJ9mKVQJ8=
singeNode: true  #单节点测试模式

